### ISSUE TITLE
[1.20.1 Fabric] Friend's world crashed as soon as he entered the dimension on Essentials server with modpack.

### ISSUE THREAD

**Issue by ZioPrime** [MC-U-Team/Overworld-Mirror#69]
### Bug description and reproduction steps

1. Load Minecraft Modpack.
2. Attempt to enter dimension on Essentials server.
3. The entire server crashes and singleplayer world cannot be accessed due to crash on on load.

### Log files and Screenshots

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2023-11-12 22:17:18
Description: Exception in server tick loop

java.lang.AbstractMethodError: Receiver class info.u_team.overworld_mirror.level.CustomTimeLevelInfo does not define or inherit an implementation of the resolved method 'abstract dev.onyxstudios.cca.api.v3.component.ComponentContainer getComponentContainer()' of interface dev.onyxstudios.cca.api.v3.component.ComponentProvider.
    at dev.onyxstudios.cca.internal.level.ComponentsLevelNetworking.lambda$init$0(ComponentsLevelNetworking.java:52)
    at dev.onyxstudios.cca.api.v3.world.WorldSyncCallback.lambda$static$1(WorldSyncCallback.java:37)
    at net.minecraft.class_3324.handler$cml000$cardinal-components-world$sendWorldInfo(class_3324.java:5022)
    at net.minecraft.class_3324.method_14606(class_3324.java:741)
    at net.minecraft.class_3324.method_14570(class_3324.java:258)
    at net.minecraft.class_3248.method_33800(class_3248.java:131)
    at net.minecraft.class_3248.md3c930e$polymer-networking$lambda$polymerNet$prePlayHandshakeHackfest$0$0(class_3248.java:549)
    at eu.pb4.polymer.networking.impl.EarlyConnectionMagic.lambda$handle$0(EarlyConnectionMagic.java:32)
    at eu.pb4.polymer.networking.api.EarlyPlayNetworkHandler.lambda$onKeepAlive$0(EarlyPlayNetworkHandler.java:108)
    at net.minecraft.class_3738.run(class_3738.java:18)
    at net.minecraft.class_1255.method_18859(class_1255.java:156)
    at net.minecraft.class_4093.method_18859(class_4093.java:23)
    at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
    at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
    at net.minecraft.class_1255.method_16075(class_1255.java:130)
    at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
    at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
    at net.minecraft.class_1255.method_5383(class_1255.java:115)
    at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742)
    at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
    at java.base/java.lang.Thread.run(Thread.java:833)

### Used minecraft version

1.20.x

### Used forge or fabric version

Fabric

### Used mod version

1.7.0.23

**Comment by Gamerbolts** [comment]
This has happened with me using the same version. I was testing my modpack and went into the dimension and crashed and keep crashing upon reloading server. Here is my log and crashlog

[latest.log](https://github.com/MC-U-Team/Overworld-Mirror/files/13923881/latest.log)
[crash-2024-01-12_14.37.40-server.txt](https://github.com/MC-U-Team/Overworld-Mirror/files/13923882/crash-2024-01-12_14.37.40-server.txt)
